### ISSUE TITLE
add one more output field: hostname

### ISSUE THREAD

**Issue by danielmotaleite** [MickayG/moby-kafka-logdriver#9]
your output info are the usual output... but i always missed one more output, the docker host hostname. It do not exists usually because the containers do not know almost any host info.... but a logger plugin is running in the host, so it could fetch that info and send it.

For most people, this is useless info, but not everyone uses random AWS machines and even with then, one may want to debug some problem, so knowing where the affected container is can save time, we can ssh directly to it instead of first having to search where that container is located.

Thanks
Daniel

**Comment by MickayG** [comment]
Completed and merged in PR #10  . Will be in the next release in a few days
